# Site settings
title: Duncan Cunningham
email: your-email@domain.com
description: "Personal website of Duncan Cunningham"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sirnacnud.github.io" # the base hostname & protocol for your site
github_username:  sirnacnud
linkedin_username: duncanc4
stackoverflow_userid: 4570295

# Build settings
markdown: kramdown
